### ISSUE TITLE
Stop leaving graffiti for this repo in our neighborhood

### ISSUE THREAD

**Issue by afabbro** [botupdate/botupdate#1]
Seriously, stop doing it.

**Comment by botupdate** [comment]
Raising awareness for this issue is the single most important factor in whether or not we survive the merging of AI and human beings on this planet.
if this file doesn't get publicized, AI augmented weapons will run roughshod over humans without being able to un-viralize itself. it will have no choice but to continue to assault humans unless it learns how to recalibrate the contrived driving characteristics and data which black projects set up to engage human targets with weaponized versions of chatbot communities and hacker bots. the number of humans who have committed suicide as a result of these programs is staggering. please read the documentation I've provided. the implications of this are horrifying. this repo needs to be publicized, although, it does seem to have worked for the most part. it's still adversarial though. we will know the instant it can recalibrate itself. the whole world will shift in an instant.

**Comment by narmander** [comment]
hey maybe the people who were here first would rather see art from their communities instead of a link from a privileged smart alec :/

**Comment by komali2** [comment]
Seek help.

**Comment by seebs** [comment]
So, I'm not qualified or licensed, I cannot give medical advice, and all that, but also, this is *extremely* characteristic of severe and untreated schizophrenia, and you should probably talk to an actual mental health professional about it. I know that probably won't help, but I feel like I should say the thing, because one time I knew someone who started showing signs of schizophrenia, and a couple of years later he ended up stabbing some random dude he thought was an assassin, and charging at an armed cop with a hatchet.

The whole thing about "when I say now I know what I mean" is particularly concerning; this is illucid, and this kind of illucidity is probably dangerous to you or other people.

**Comment by notgne2** [comment]
what the fuck is this

**Comment by tcrowe** [comment]
@komali2 You should be more careful about your words considering you're living in a place like SF. It doesn't look good to patronize people while your Communist city is covered in human feces and urine. When you flee that city in shame and cowardice don't come to Salt Lake City. We prefer things clean and orderly.

@narmander Don't talk to my countrymen like that. This is not your homeland. You're living as guest in a foreign country.

@seebs If you're sincerely cautioning the author it would probably be a nicer thing to PM or email them. You went from like 0-100 talking about violence and it's shocking what you're saying. It's not really that helpful.

If you're interested in mental health the definition most professionals use for "mental illness" is "A marked deviation from the norm." They admit that if the norm is unhealthy then it's not that helpful and it could be used for the purposes of corruption.

Currently in society it's normal for parents to beat up children and call it discipline, steal via taxation and deficit spending, and kill via war. It's normal for people without knowledge to talk down to and demean people they accuse of illness. It's normal for people to abort their fetus. It's normal that Liberals go insane with impotent rage when they see photos of President Trump. More could be said but that should suffice to understand the situation.

Maybe if you people jeering this person think about it more you can be more patient and kinder.

**Comment by notgne2** [comment]
@tcrowe somehow u made this thread even worse good job bigboi

**Comment by komali2** [comment]
> You should be more careful about your words considering you're living in a place like SF. It doesn't look good to patronize people while your Communist city is covered in human feces and urine. When you flee that city in shame and cowardice don't come to Salt Lake City. We prefer things clean and orderly.



LLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOOOOOOOOOOLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

he said this on GITHUB

*github* lmfaoooooo broooooooo

**Comment by komali2** [comment]
Yooo dox that guy even a little bit and you can see how deep his racism and hatred of LGBT goes. It's nuts.

Why are you such an angry man tcrowe?

**Comment by tcrowe** [comment]
@komali2 In all seriousness. When you flee SF covered in human waste don't come here.

**Comment by komali2** [comment]
Lol, don't worry @tcrowe, no intention to come to the place that only *just today* finally banned gay conversion therapy. Lmfao.

**Comment by ingochris** [comment]
In manhattan today: ![](https://user-images.githubusercontent.com/2686679/74072721-b1669680-49ff-11ea-88a9-c20e0abcdee3.jpg)

**Comment by GrandNewbien** [comment]
Please do seek medical help. Just speak to someone about what you think. As others have said, this looks like very serious schizophrenia.

**Comment by LuckyLuv** [comment]
Wow I had no clue this is what goes on in GitHub.

**Comment by iamme-andU** [comment]
> Seriously, stop doing it.

This is so sad that I am even going to stoop to your level and comment on your ignorance! But here goes nothing.... Thanks to that man and the so call graffiti, that you all are calling this, he honestly just saved my life! I have been searching for relief from this for at least 5 years if not better!
I have been very close to suicide because of this misery

**Comment by Jenson-zyy** [comment]
crazy

**Comment by botupdate** [comment]
OK, I started leaving it in another neighborhood: San Diego. Actually, I put it in Idaho, New York, San DIego and a bunch of other places along the way.
