### ISSUE TITLE
Get some serious help

### ISSUE THREAD

**Issue by Nightspeedy** [botupdate/botupdate#12]
Dude, you need to go talk to a psychologist about this bs man, STOP LEAVING YOUR LINKS ALL OVER TOWN!

**Comment by joshoftenly** [comment]
this is a schizophrenic break. 

I've worked with veterans with PTSD and this seems a lot like that, though it's likeliest the severest I've seen. 

Please get some help friend. The VA has free healthcare. I hope you are ok. 

also please keep writing because I've enjoyed that. But you do need help.

**Comment by NARKOZ** [comment]
Really? There are tons of ads everywhere and no one complains, but a small harmless graffiti suddenly become an issue? Wow. Have some respect, stop telling others what to do, stop judging and attacking other people.

I understand that such work may seem crazy at first, but unless the author is diagnosed by a professional there is no way to tell (besides they already ruled out this in https://github.com/botupdate/botupdate/issues/18).

**Comment by chizzel36** [comment]
#18

**Comment by komali2** [comment]
Claiming that the people saying "seek help" are federal agents possibly employing hypnosis or targeted energy weapons, believe it or not, do not "rule out" schizophrenia.
