### ISSUE TITLE
Paragraphs, Chapters and sentences that make sense

### ISSUE THREAD

**Issue by joshoftenly** [botupdate/botupdate#17]
As I was reading through this I noticed that many of the blocks of text don't have paragraphs. I realize it's tough to write when you're on Meth/DMT but still I feel like some paragraphs would help us all. 

Breaking things into chapters would also be a good help. 

Sentences usually stick to one thought. Please try to make the sentences a bit more clear. 

Also, former navy guy here. Love the Marines, the VA has free healthcare and you need to seek some help. Writing is good therapy but like... yeah, you need some help. Please go get the help you need.

**Comment by botupdate** [comment]
This was written over a. Of 2 years when I didn't always have time to edit so I didn't want to lose the thought and I just stuck it in there and I just cleaned up a lot of the old files and I'm going over the main file today to take out a bunch of extraneous stuff since it's like 60 pages long and I think I can really knock it down the 20 but that's why I have it on get home so people can help with that
