### ISSUE TITLE
Ruling out Schizophrenia as an explanation

### ISSUE THREAD

**Issue by botupdate** [botupdate/botupdate#18]
Thank you for taking the time to offer suggestions about The Bot Update

> So, I'm not qualified or licensed, I cannot give medical advice, and all that, but also, this is _extremely_ characteristic of severe and untreated schizophrenia, <

Thank you for honesty, qualifying your level of professional medical credibility before offering your diagnosis, treatment options and case history of an illness which does not include the conditions I describe; such as "delusions" which ask you to believe in their nonexistence as a tactic for continuing to harass and distract a person. This kind of irrational dialogue is a known/published tactic for adversarial intelligence agencies to gather evidence while marginalizing persons who are being considered as a threat for a variety of reasons (also published as a part of the "Patriot Act" and other programs I list in the "articles" section). 

In the case of your hatchet-weilding friend, I hope that he survived the incident with the police. Attacking surveillance personel who trample the philosophy and laws that our forefathers so specifically addressed in the framing of the US Constitution and Bill Of Rights is not a symptom of mental illness in my opinion; and hardly as dangerous as starting a revolution. Even George Washington was rumored to have taken a few imprudent swings with a hatchet in his youth; to be honest, I feel obliged to argue that surveillance professionals' behavior in the modern era is probably more deserving of the axe than our first President's innocent, fruit-bearing, cherry tree.

To address your comment about the following statement which seems lto have been lacking the context of my attempt to identify or eliminate hypnosis as a factor:

> The whole thing about "when I say now I know what I mean" is particularly concerning; this is illucid, and this kind of illucidity is probably dangerous to you or other people.<

The context of this comment was that I was aware of hypnosis as a possible explanation for some of the strange observations and conditions I'm experiencing; and that It seems to me that shouldn't necessarily need to speak specific dialogue to ignore/change a condition which my brain is somehow agreeing to irrationally follow; since, I know what I mean when I make the statement to disable the hypnosis which I would have never agreed to in any case.

Thank you for your comments, I will make sure that is stated clearly in case it sounds illucid to anyone else.

**Comment by botupdate** [comment]
I have seen a few articles and comments which compare diagnoses for Schizophrenia in the US before and after these weapons were developed and I believe that it proves that this is identifiable and detrimental to the medical community because of the potentially misleading number of misdiagnosed cases of schizophrenia.

The following was posted so well on Reddit.com/r/TargetedEnergyWeapons that I had to just leave it right here:

https://www.reddit.com/r/TargetedEnergyWeapons/comments/d9u0wb/voices_consciously_heard_submit_biomarker_lab/?utm_medium=android_app&utm_source=share

**Comment by komali2** [comment]
> This kind of irrational dialogue is a known/published tactic for adversarial intelligence agencies to gather evidence while marginalizing persons who are being considered as a threat for a variety of reasons 

Hi, feel free to dox me, it's pretty easy to find out that I'm not a federal agent - considering I'm a communist ;) 

Seek help bro. You're talking about shit like targeted energy weapons and hypnosis. 

At the very least stop graffitiing.

**Comment by wethepeople1776** [comment]
Please note that it is just as dangerous to falsely label someone as schizophrenic as it is to give a false negative.

Moreover, my two cents:
This man’s speech fails to exhibit certain key characteristics of schizophrenia disorder per the DSM. He makes concerted effort to organize his statements. Sufferers of schizoaffective disorders are generally unable to separate their dialogue from whatever psychosomatic state that they’re in, whether depressive or manic. To the contrary, this man‘s words exhibit a remarkable level of personal control and reflection. In other words, it’s unlikely that he suffers from anything non-environmental; mental illness is far too potent for one to be able to express him/her-self.

**Comment by botupdate** [comment]
Thank you for your concern, I am doing my best to write this cogently and effectively. at this point I don't care about the haters, any exposure is good exposure for those who are still suffering, I will say that this definitely works for targeted individuals who are being assaulted by neural networks.

**Comment by thima2017** [comment]
I heard that nobody really nose what schizophrenia really is. I guess that it's either a protection behavior guardian angel makes human do or think to protect that human from incoming demons or, if guardian angel failed, it's just a demons harassment. And some psychiatric drugs are able to break the link between the physical and "non-physical" worlds. Like a firewall. But I guess it's a temporal solution and human need an angel or angels collective to keep all the supernatural things out of the normal human life. And a kind of discipline of thoughts is needed sometimes too. I guess the author found a solution by calling for a new angel and tries to help others here. And I hope the new angel aren't an ally of the harassment demons. Because in that case it could be just a demon spreading place, when one thinks he is helping, but he doesn't. 
And of course nothing can prevent demons from making and using an AI. And it looks like a very convenient cover for an antichrist for example. It would work for atheists and for religious people. So drawing a public attention to this problem is a good thing too.

**Comment by thima2017** [comment]
And people say that a point of such harassment is to make human suicide to take the soul and wipe theirs traces. Because they don't want to be found, for some reason. That's why the more we wish to suicide the less we should do it. Suicide is a much more terrible trap than anything here. 
Sometimes God changes the final result of an intention, but not the intention itself.
