### ISSUE TITLE
Objective method of validation or invalidation

### ISSUE THREAD

**Issue by tcrowe** [botupdate/botupdate#2]
@botupdate There's a lot to read here so I was wondering if you could link to a method to validate and invalidate the existence of the `adversarial neural network.`

What is the scale?

What is the matter?

How can it be measured?

What test would disprove the existence of it?

**Comment by botupdate** [comment]
Those are excellent questions which I do not know how to quantify other than personal experience; except that I there are plenty of known examples of this type of neural network in existence and therefore; as a former Marine I can reasonably assume that someone has been using this as a weapon or a method of penetrating other networks. Because I also know that these techniques have been used against american delegates in Cuba and China and this happened after I identified it happening to me, I'm still unable to provide much in the way of proof because I have no resources. I'm homeless in New York as a result of this program destroying my businesses. I need help.

David Williams
215.500.6494

**Comment by iamme-andU** [comment]
I came across a profile of a person named Jamie-:)_ they must have me blocked, They seem to be decoding my stuff and listening into my phone conversations causing them to drop, and he was right on this very site github! After I seen they were actual people that is when I started being stalked in person and they were repeating my phone conversations I had with my kids doctors back to me like it was there life. It was numerous of people doing it to me! 


 They take over every account administration I make also if u look up jgallagher@bignerdranch.com I found forums on github profile about the same stuff on my device. That  may lead you somewhere also!  One other thing I was redirected to a USMC MD5 Challange of data sourcing from July 2018- September 2018. He isn’t wrong they are using military and government crap to do it.  I also notice a bunch of Europuen Union privacy policies  I have to allow also! 
I was told that the analytics on my iPhone XR showed signs of the Heartbleed attack that hit the United States about 5 years to 8 years ago. Anyway keep me posted please Thanks
